"Pre and post open."

diff --git a/open b/open
--- a/open
+++ b/open
@@ -7,8 +7,36 @@ echo "Opening the HelixTrack Core"
 HERE=$(pwd)
 
 SCRIPT_DO_OPEN="$HERE/do_open"
+SCRIPT_PRE_OPEN="$HERE/pre_open"
+SCRIPT_POST_OPEN="$HERE/post_open"
+
+if test -e "$SCRIPT_PRE_OPEN"; then
+
+    if sh "$SCRIPT_PRE_OPEN"; then
+
+        echo "Pre-open completed"
+
+    else
+
+        echo "ERROR: Pre-open failed"
+        exit 1
+    fi
+fi
 
 if test -e "$SCRIPT_DO_OPEN"; then
 
   sh "$SCRIPT_DO_OPEN"
+fi
+
+if test -e "$SCRIPT_POST_OPEN"; then
+
+    if sh "$SCRIPT_POST_OPEN"; then
+
+        echo "Post-open completed"
+
+    else
+
+        echo "ERROR: Post-open failed"
+        exit 1
+    fi
 fi
