"Load .rc variables if not (re)loaded."

diff --git a/open b/open
--- a/open
+++ b/open
@@ -3,39 +3,6 @@
 # TODO: Clone script to download the opening files and scripts that are not the part of Project Toolkit
 
 HERE=$(pwd)
-DIR_HOME=$(eval echo ~"$USER")
-
-if [ -z "$SUBMODULES_HOME" ]; then
-
-    FILE_ZSH_RC="$DIR_HOME/.zshrc"
-    FILE_BASH_RC="$DIR_HOME/.bashrc"
-
-    if test -e "$FILE_ZSH_RC"; then
-
-        FILE_RC="$FILE_ZSH_RC"
-
-    else
-
-        if test -e "$FILE_BASH_RC"; then
-
-        FILE_RC="$FILE_BASH_RC"
-
-        else
-
-        echo "ERROR: No '$FILE_ZSH_RC' or '$FILE_BASH_RC' found on the system"
-        exit 1
-        fi
-    fi
-
-    # shellcheck disable=SC1090
-    . "$FILE_RC"
-fi
-
-if [ -z "$SUBMODULES_HOME" ]; then
-
-  echo "ERROR: The 'SUBMODULES_HOME' variable is not defined"  
-  exit 1
-fi
 
 SCRIPT_DO_OPEN="$HERE/do_open"
 SCRIPT_PRE_OPEN="$HERE/pre_open"
@@ -50,6 +17,11 @@ if test -e "$SCRIPT_PRE_OPEN"; then
     fi
 fi
 
+if [ -z "$SUBMODULES_HOME" ]; then
+
+  echo "ERROR: The 'SUBMODULES_HOME' variable is not defined"  
+  exit 1
+fi
 
 SCRIPT_PREPARE_LOCAL="$HERE/prepare"
 
