"Auto-commit "

diff --git a/pre_open b/pre_open
--- a/pre_open
+++ b/pre_open
@@ -63,3 +63,18 @@ else
 
   echo "Project Toolkit is available at '$SUBMODULES_HOME'"
 fi
+
+DIR_MODULE_UPSTREAMABLE="$SUBMODULES_HOME/Upstreamable"
+
+SCRIPT_PATHS="$SUBMODULES_HOME/Software-Toolkit/Utils/Sys/paths.sh"
+
+if ! test  -e "$SCRIPT_PATHS"; then
+
+    echo "ERROR: Prepare script not found '$SCRIPT_PATHS'"
+    exit 1
+fi
+
+# shellcheck disable=SC1090
+. "$SCRIPT_PATHS"
+
+ADD_TO_PATH "$FILE_RC" "$DIR_MODULE_UPSTREAMABLE"
