Testing, fixing and polishing.

diff --git a/pre_open b/pre_open
--- a/pre_open
+++ b/pre_open
@@ -62,14 +62,23 @@ if [ "$FILES_COUNT" == 0 ]; then
     fi
   fi
 
-  if (wget "https://raw.githubusercontent.com/red-elf/Project-Toolkit/main/clone?append="$(($(date +%s%N)/1000000)) -O clone) && \
-    chmod +x ./clone && ./clone git@github.com:red-elf/Project-Toolkit.git /tmp; then
+  if wget "https://raw.githubusercontent.com/red-elf/Project-Toolkit/main/clone?append="$(($(date +%s%N)/1000000)) -O clone; then
+  
+    echo "Clone script is ready"
 
-    echo "Project Toolkit is installed to '$SUBMODULES_HOME'"
+    if chmod +x ./clone && ./clone git@github.com:red-elf/Project-Toolkit.git /tmp; then
+
+      echo "Project Toolkit is installed to '$SUBMODULES_HOME'"
+
+    else
+
+      echo "ERROR: Project Toolkit is not installed to '$SUBMODULES_HOME' (2)"
+      exit 1
+    fi
 
   else
 
-    echo "ERROR: Project Toolkit is not installed to '$SUBMODULES_HOME'"
+    echo "ERROR: Project Toolkit is not installed to '$SUBMODULES_HOME' (1)"
     exit 1
   fi
 
