Update routine improved.

diff --git a/pull_all b/pull_all
--- a/pull_all
+++ b/pull_all
@@ -1,7 +1,35 @@
 #!/bin/bash
 
-if ! git fetch && git pull && git submodule init && git submodule update; then
+if git fetch; then
 
-  echo "ERROR: Could not update"
+  if git pull; then
+
+    if git submodule init; then
+
+      if git submodule update; then
+
+        echo "Update OK"
+
+      else
+
+        echo "ERROR: Could not update (4)"
+        exit 1
+      fi
+
+    else
+
+      echo "ERROR: Could not update (3)"
+      exit 1
+    fi
+
+  else
+
+    echo "ERROR: Could not update (2)"
+    exit 1
+  fi
+
+else
+
+  echo "ERROR: Could not update (1)"
   exit 1
 fi
